apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clue-arena-app.serviceAccountName" . }}
  labels:
    {{- include "clue-arena-app.labels" . | nindent 4 }}
automountServiceAccountToken: false
